apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: simple
spec:
  releaseName: simple
  chart:
    spec:
      version: "${version}"
      chart: simple
      sourceRef:
        kind: HelmRepository
        name: ${helmRepository}
        namespace: flux-system
  interval: 5m
  install:
    disableWait: true
  upgrade:
    disableWait: true
  values:
    ingress:
      enabled: true # ${ingressEnabled:="false"}
      hostname: ${hostname}
      # ingressClassName: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
  valuesFrom:
    - kind: ConfigMap
      name: default-values
      valuesKey: default-values.yaml
    - kind: ConfigMap
      name: simple-resource-values
      valuesKey: simple-resource-values.yaml
      optional: true
